{
 "title": "Scaleway Database overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (name) (scaleway_database_cpu_usage_percent)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (name) (scaleway_database_memory_usage_percent)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (name) (scaleway_database_disk_usage_percent)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by (name) (scaleway_database_total_connections)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}